package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const fileTemplate = `// Code generated by "reset"; DO NOT EDIT.

package {{.Package}}

{{- range .Methods }}

{{ . }}
{{- end }}
`

type fileTplData struct {
	Package string
	Methods []string
}

func main() {
	root := "." // корень проекта
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return processDir(path)
		}
		return nil
	})
	if err != nil {
		log.Fatal(err)
	}
}

// processDir сканирует пакет и генерирует reset.gen.go
func processDir(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		// не анализируем сгенерённые файлы и файл генератора (на всякий)
		name := fi.Name()
		if strings.HasSuffix(name, "_gen.go") {
			return false
		}
		if name == "reset.gen.go" {
			return false
		}
		return true
	}, parser.ParseComments)
	if err != nil {
		return err
	}

	for pkgName, pkg := range pkgs {
		methods := make([]string, 0, 8)

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE {
					continue
				}

				for _, spec := range gen.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}

					// проверяем комментарий // generate:reset
					if !hasGenerateResetComment(gen.Doc) {
						continue
					}

					methodCode := generateResetMethod(ts.Name.Name, st)
					methods = append(methods, methodCode)
				}
			}
		}

		if len(methods) == 0 {
			continue
		}

		out, err := renderFile(fileTplData{
			Package: pkgName,
			Methods: methods,
		})
		if err != nil {
			return err
		}

		// gofmt
		out, err = format.Source(out)
		if err != nil {
			// если форматирование не удалось — возвращаем сырой код,
			// но не падаем без причины (можно сделать return err, если хочешь строже)
			// здесь оставим строгий вариант:
			return fmt.Errorf("format generated code: %w", err)
		}

		outFile := filepath.Join(dir, "reset.gen.go")
		if err := os.WriteFile(outFile, out, 0644); err != nil {
			return err
		}
		fmt.Println("Generated:", outFile)
	}

	return nil
}

func renderFile(data fileTplData) ([]byte, error) {
	tpl, err := template.New("reset.gen.go").Parse(fileTemplate)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := tpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func hasGenerateResetComment(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.TrimSpace(c.Text) == "// generate:reset" {
			return true
		}
	}
	return false
}

// generateResetMethod создаёт метод Reset() для структуры
func generateResetMethod(name string, st *ast.StructType) string {
	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("func (s *%s) Reset() {\n", name))
	buf.WriteString("\tif s == nil {\n\t\treturn\n\t}\n\n")

	for _, f := range st.Fields.List {
		// embedded fields (без имени) — можно пропустить или обработать отдельно
		if len(f.Names) == 0 {
			continue
		}
		for _, fname := range f.Names {
			fieldCode := generateFieldReset(fname.Name, f.Type)
			if fieldCode == "" {
				continue
			}
			// fieldCode уже может быть многострочным с табами
			lines := strings.Split(fieldCode, "\n")
			for _, ln := range lines {
				buf.WriteString("\t" + ln + "\n")
			}
		}
	}

	buf.WriteString("}")
	return buf.String()
}

// generateFieldReset создаёт код сброса конкретного поля
func generateFieldReset(fieldName string, expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"uintptr",
			"float32", "float64",
			"complex64", "complex128":
			return fmt.Sprintf("s.%s = 0", fieldName)
		case "string":
			return fmt.Sprintf("s.%s = \"\"", fieldName)
		case "bool":
			return fmt.Sprintf("s.%s = false", fieldName)
		default:
			// если поле — интерфейс или тип с методом Reset
			return fmt.Sprintf(
				"if r, ok := any(s.%s).(interface{ Reset() }); ok {\n\tr.Reset()\n}",
				fieldName,
			)
		}

	case *ast.StarExpr:
		// указатель: *T
		switch inner := t.X.(type) {
		case *ast.Ident:
			// указатель на примитив
			switch inner.Name {
			case "int", "int8", "int16", "int32", "int64",
				"uint", "uint8", "uint16", "uint32", "uint64",
				"uintptr",
				"float32", "float64",
				"complex64", "complex128":
				return fmt.Sprintf("if s.%s != nil {\n\t*s.%s = 0\n}", fieldName, fieldName)
			case "string":
				return fmt.Sprintf("if s.%s != nil {\n\t*s.%s = \"\"\n}", fieldName, fieldName)
			case "bool":
				return fmt.Sprintf("if s.%s != nil {\n\t*s.%s = false\n}", fieldName, fieldName)
			default:
				// указатель на структуру/тип с Reset
				return fmt.Sprintf("if s.%s != nil {\n\ts.%s.Reset()\n}", fieldName, fieldName)
			}
		default:
			// сложный тип под указателем — безопасно вызываем Reset при наличии
			return fmt.Sprintf("if s.%s != nil {\n\ts.%s.Reset()\n}", fieldName, fieldName)
		}

	case *ast.ArrayType:
		// слайсы и массивы:
		// Если это slice: *ast.ArrayType{Len:nil} — ставим nil
		// Если это массив: Len != nil — зануляем весь массив присваиванием нулевого значения
		if t.Len == nil {
			return fmt.Sprintf("s.%s = nil", fieldName)
		}
		return fmt.Sprintf("s.%s = %s{}", fieldName, exprString(expr))

	case *ast.MapType:
		// Go 1.21+: built-in clear
		return fmt.Sprintf("clear(s.%s)", fieldName)

	case *ast.SelectorExpr:
		// например time.Time или sql.NullString
		return fmt.Sprintf("s.%s = %s{}", fieldName, exprString(expr))

	default:
		return fmt.Sprintf("// TODO reset %s", fieldName)
	}
}

// exprString возвращает исходный код выражения
func exprString(expr ast.Expr) string {
	var buf bytes.Buffer
	_ = printer.Fprint(&buf, token.NewFileSet(), expr)
	return buf.String()
}

// generate:reset
type URLMapping struct {
	ID      int
	URL     string
	Tags    []string
	Options map[string]string
	Child   *URLMapping
}
